export const auth = {
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',
  LOGOUT: 'LOGOUT',
};

export const tool = {
  FETCH_TOOLS: 'FETCH_TOOLS',
  FETCH_TOOL: 'FETCH_TOOL',
};

export const order = {
  FETCH_ALL: 'FETCH_ALL',
  FETCH_BUGS_ORDERS: 'FETCH_BUGS_ORDERS',
  FETCH_FEATURES_ORDERS: 'FETCH_FEATURES_ORDERS',
  FETCH_ORDER: 'FETCH_ORDER',
  ERR: 'ERR',
  SUCCES: 'SUCCES',
  TOOGLE_VIEW: 'TOOGLE_VIEW',
};
